# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  build:
    docker:
    - image: circleci/node:10.6
    working_directory: ~/repo
    steps:
    - add_ssh_keys:
        fingerprints:
        - "65:11:ab:26:27:34:f3:30:34:9c:22:d6:9e:aa:0d:1e"
        - "0a:f5:ce:05:50:dd:b6:f7:d4:51:ae:26:cc:14:c0:dc"
        - "e3:88:19:c6:ff:e6:a4:c5:89:b6:3d:13:e4:df:49:ed"

    - deploy:
        name: digital-ocean
        command: ssh -o "StrictHostKeyChecking no" dev@partymaker.zp.ua "cd ~/partymaker/backend; ./build.sh"
